name: Infracost CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  infracost:
    runs-on: ubuntu-latest
    name: Infracost Diff
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Debug Start
        run: |
          echo "Job started at $(date)"
          echo "Runner OS: $(uname -a)"
          echo "Event Name: ${{ github.event_name }}"
          echo "Event Action: ${{ github.event.action }}"
          echo "PR User: ${{ github.event.pull_request.user.login }}"
          echo "GitHub Context: ${{ toJson(github) }}"

      - name: Setup Infracost
        uses: infracost/actions/setup@v2
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: List repository files
        run: |
          pwd
          ls -R .
          echo "Current directory contents: $(ls -a)"

      - name: Detect config file path
        id: detect
        run: |
          CONFIG_PATH="workspaces/kubernetes/prod/main/infracost.yml"
          if [ -f "$CONFIG_PATH" ]; then
            echo "CONFIG_PATH=$CONFIG_PATH" >> $GITHUB_ENV
            echo "Detected Infracost config at: $CONFIG_PATH"
          else
            echo "Infracost.yml not found at $CONFIG_PATH in PR branch. Exiting..."
            exit 1
          fi

      - name: Checkout base branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Generate Infracost baseline
        run: |
          if [ -f "$CONFIG_PATH" ]; then
            infracost breakdown \
              --config-file="$CONFIG_PATH" \
              --format=json \
              --out-file=/tmp/infracost-base.json
          else
            echo "Missing config at $CONFIG_PATH in base branch"; exit 1
          fi

      - name: Checkout PR branch again
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Generate Infracost diff
        run: |
          infracost diff \
            --config-file="$CONFIG_PATH" \
            --format=json \
            --compare-to=/tmp/infracost-base.json \
            --out-file=/tmp/infracost.json

      - name: Post Infracost comment
        run: |
          infracost comment github \
            --path=/tmp/infracost.json \
            --repo=$GITHUB_REPOSITORY \
            --github-token=${{ github.token }} \
            --pull-request=${{ github.event.pull_request.number }} \
            --behavior=update

      - name: Upload Infracost report to Cloud
        env:
          INFRACOST_VCS_REPOSITORY_URL: https://github.com/${{ github.repository }}
          INFRACOST_VCS_PULL_REQUEST_URL: https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}
          INFRACOST_VCS_BRANCH: ${{ github.head_ref || github.ref_name }}
          INFRACOST_VCS_COMMIT_SHA: ${{ github.sha }}
        run: |
          infracost upload --path=/tmp/infracost.json

      - name: Debug End
        run: |
          echo "Job completed at $(date)"
